"""Idempotent merge of the '## Writing conventions' block into `_venue.md`.

The aggregated writing-conventions body lives between sentinel HTML comments so
re-running `/paper venue refs distill` can replace only that span — manual edits
elsewhere in `_venue.md` survive byte-for-byte.
"""

from __future__ import annotations

import os
import re
from pathlib import Path

SENTINEL_BEGIN = "<!-- venue-refs:begin -->"
SENTINEL_END = "<!-- venue-refs:end -->"
CONVENTIONS_HEADING = "## Writing conventions"
_AUTO_NOTE = (
    "_Auto-generated by /paper venue refs distill — "
    "edits inside this block will be overwritten. Manual edits outside survive._"
)
_HEADING_RE = re.compile(r"^##\s+Writing conventions\s*$", re.MULTILINE)
_NEXT_HEADING_RE = re.compile(r"^##\s", re.MULTILINE)


def upsert_writing_conventions(venue_md: Path, block_body: str) -> None:
    """Idempotently install or replace the '## Writing conventions' block.

    `block_body` is the markdown that goes *inside* the section (no heading, no
    sentinels — both are added by this function). Writes atomically.
    """
    venue_md = Path(venue_md)
    if not venue_md.is_file():
        raise FileNotFoundError(f"_venue.md not found: {venue_md}")

    text = venue_md.read_text(encoding="utf-8")
    new_text = _replace_or_insert(text, block_body)
    _atomic_write(venue_md, new_text)


def extract_writing_conventions(venue_md_text: str) -> str | None:
    """Return the body between sentinels (heading + sentinels stripped), or None."""
    begin = venue_md_text.find(SENTINEL_BEGIN)
    if begin == -1:
        return None
    end = venue_md_text.find(SENTINEL_END, begin + len(SENTINEL_BEGIN))
    if end == -1:
        return None
    inner = venue_md_text[begin + len(SENTINEL_BEGIN) : end]
    # Strip the auto-note line if present
    inner = re.sub(r"^\s*" + re.escape(_AUTO_NOTE) + r"\s*\n", "", inner, count=1)
    return inner.strip("\n")


# ---------- internals ----------

def _render_block(block_body: str) -> str:
    body = block_body.rstrip("\n")
    return (
        f"{CONVENTIONS_HEADING}\n"
        f"{SENTINEL_BEGIN}\n"
        f"{_AUTO_NOTE}\n"
        f"\n"
        f"{body}\n"
        f"{SENTINEL_END}"
    )


def _replace_or_insert(text: str, block_body: str) -> str:
    begin_count = text.count(SENTINEL_BEGIN)
    end_count = text.count(SENTINEL_END)
    if begin_count != end_count or begin_count > 1:
        raise ValueError(
            "Corrupted writing-conventions block in _venue.md "
            "(mismatched or duplicated sentinels) — fix manually or delete the block."
        )

    rendered = _render_block(block_body)

    # Case 1: sentinel-fenced block exists → replace span including the heading line
    # immediately above the begin sentinel if present.
    if begin_count == 1:
        begin = text.find(SENTINEL_BEGIN)
        end = text.find(SENTINEL_END, begin) + len(SENTINEL_END)
        # Walk back to the start of the line containing the begin sentinel, then
        # if the previous line is the conventions heading, swallow it too so the
        # rendered block (which includes the heading) doesn't duplicate it.
        line_start = text.rfind("\n", 0, begin) + 1
        prev_line_end = line_start - 1  # position of the '\n' before line_start, or -1
        prev_line_start = text.rfind("\n", 0, prev_line_end) + 1 if prev_line_end > 0 else 0
        prev_line = text[prev_line_start:prev_line_end] if prev_line_end > 0 else ""
        # The regex permits optional trailing whitespace, but prev_line.strip()
        # has already removed it — an exact equality check covers both forms.
        if prev_line.strip() == CONVENTIONS_HEADING:
            replace_start = prev_line_start
        else:
            replace_start = line_start
        return text[:replace_start] + rendered + text[end:]

    # Case 2: heading present without sentinels → replace heading through next `## ` or EOF.
    heading_match = _HEADING_RE.search(text)
    if heading_match:
        start = heading_match.start()
        rest_offset = heading_match.end()
        next_match = _NEXT_HEADING_RE.search(text, rest_offset)
        if next_match:
            end = next_match.start()
            # Drop trailing blank line(s) from the replaced span so layout stays clean.
            replaced = rendered + "\n\n"
            return text[:start] + replaced + text[end:]
        else:
            replaced = rendered + "\n"
            return text[:start].rstrip("\n") + "\n\n" + replaced

    # Case 3: append at end of file.
    prefix = text.rstrip("\n")
    sep = "\n\n" if prefix else ""
    return f"{prefix}{sep}{rendered}\n"


def _atomic_write(path: Path, content: str) -> None:
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(content, encoding="utf-8")
    os.replace(tmp, path)
